image:
  name: docker

services:
  - docker:dind

stages:
  - build
  - test
  - publish-image
  - deploy

variables: 
  IMAGE_BUILD_NAME: vitormcruz_employees_$CI_PIPELINE_ID
  IMAGE_NAME: $CI_REGISTRY/vitormcruz/employees

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  
build_image:
  stage: build
  
  script:
    - docker build -t $IMAGE_BUILD_NAME .
    - docker save $IMAGE_BUILD_NAME > $IMAGE_BUILD_NAME.tar
    
  artifacts:
    name: $IMAGE_BUILD_NAME
    expire_in: 1 hour
    paths:
      - $IMAGE_BUILD_NAME.tar
      
test_image:
  stage: test
  
  script:
    - docker load < $IMAGE_BUILD_NAME.tar
    - docker run --cap-add SYS_NICE --entrypoint bash $IMAGE_BUILD_NAME ./opt/pharo/pharo /opt/pharo/Pharo.image eval "1=1"

test_app:
  image:
    name: docker/compose:1.23.2
    entrypoint: ["/bin/sh", "-c"]
    
  stage: test
  script:
    - ls -la
    - apk update
    - apk add wget
    - docker load < $IMAGE_BUILD_NAME.tar 
    - export APP_IMAGE_NAME=$IMAGE_BUILD_NAME
    - docker-compose up &
    - sleep 60
    - wget --retry-connrefused --waitretry=5 --read-timeout=20 --timeout=15 -t 20 --server-response localhost:8080/employees
    - docker-compose stop &
  variables: 
    DOCKER_HOST: tcp://docker:2375/ 
    DOCKER_DRIVER: overlay2

push_snapshot_image:
  stage: publish-image
  except:
    - /^v:.*$/
    - tags
  
  script:
    - docker load < $IMAGE_BUILD_NAME.tar
    - docker tag $IMAGE_BUILD_NAME $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    
push_release_image:
  stage: publish-image
  only:
    - /^v-.*$/
    - tags
    
  script:
    - docker load < $IMAGE_BUILD_NAME.tar
    - docker tag $IMAGE_BUILD_NAME $IMAGE_NAME:$CI_COMMIT_TAG
    - docker push $IMAGE_NAME:$CI_COMMIT_TAG
  
