image: gitlab/dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

tests:

  script:
    - docker build --pull -t vitormcruz/employees .
    - docker run vitormcruz/employees 
    - NAME = $CI_REGISTRY/vitormcruz/employees
    - FULL_NAME = $NAME:"$(git log -1 --pretty=%H)"
    - SNAPSHOT_TAG = $NAME:snapshot
    - docker tag vitormcruz/employees $SNAPSHOT_TAG
    - docker tag vitormcruz/employees $FULL_NAME
    - docker push $FULL_NAME
    - docker push $SNAPSHOT_TAG