image: gitlab/dind

stages:
  - build
  - test
  - publish-image
  - deploy

variables: 
  IMAGE_BUILD_NAME: vitormcruz_employees_$CI_PIPELINE_ID
  IMAGE_NAME: $CI_REGISTRY/vitormcruz/employees

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  
build_image:
  stage: build
  
  script:
    - docker build --pull -t $IMAGE_BUILD_NAME .
    - docker save $IMAGE_BUILD_NAME > $IMAGE_BUILD_NAME.tar
    
  artifacts:
    name: $IMAGE_BUILD_NAME
    expire_in: 1 hour
    paths:
      - $IMAGE_BUILD_NAME.tar
      
test_image:
  stage: test
  
  script:
    - docker load < $IMAGE_BUILD_NAME.tar
    - docker run --cap-add SYS_NICE $IMAGE_BUILD_NAME

push_snapshot_image:
  stage: publish-image
  except:
    - /^v:.*$/
    - tags
  
  script:
    - docker load < $IMAGE_BUILD_NAME.tar
    - docker tag $IMAGE_BUILD_NAME $IMAGE_NAME:"$(git log -1 --pretty=%H)"
    - docker push $IMAGE_NAME:"$(git log -1 --pretty=%H)"
    
push_release_image:
  stage: publish-image
  only:
    - /^v-.*$/
    - tags
    
  script:
    - docker load < $IMAGE_BUILD_NAME.tar
    - docker tag $IMAGE_BUILD_NAME $IMAGE_NAME:v1.0.0
    - docker push $IMAGE_NAME:v1.0.0
  