version: '3'
services:
  mongo:
    image: "mongo:3.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - "mongo"

  elasticsearch:
    image: "elasticsearch:6.5.2"
    ports:
      - "9200:9200"
