version: '3'

services:
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    depends_on:
      - "mongo"

  kibana:
    image: "kibana:6.5.3"
    ports:
      - "5601:5601"
    depends_on:
      - "elasticsearch"
