version: '3'

services:
  employees:
    image: ${APP_IMAGE_NAME}
    ports:
      - 8080:8080

  mongo:
    image: "mongo:3.2"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  elasticsearch:
    image: "elasticsearch:6.5.2"
    ports:
      - "9200:9200"
